services:
  - type: web
    name: miapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DB_HOST
        value: containers-us-west-123.railway.app  # Reemplaza por el host real de tu BD en la nube
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: jhoneiderquintero12345@
      - key: DB_NAME
        value: miapp
